image: node:slim

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - yarn --frozen-lockfile
          - yarn type-check
          - yarn lint
          - yarn build
